sudo: false
language: python
os:
  - linux
python:
  - "3.6"
  - "3.7-dev"

branches:
  only:
  - master

git:
  depth: 2

cache:
  pip: true

matrix:
  fast_finish: true

install:
  - pip install --upgrade pip setuptools wheel tox tox-travis

script:
  - tox -- --cov-report=xml --cov-report=term tests

after_success:
  - bash <(curl -f https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always
    on_pull_requests: never
