sudo: false
language: python
os:
  - linux
python:
  - "3.6"
  - "3.7-dev"

branches:
  only:
  - master

git:
  depth: 2

cache:
  pip: true

matrix:
  fast_finish: true

install:
  - pip install --upgrade pip setuptools wheel tox tox-travis

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - tox -- --cov-report=xml --cov-report=term tests

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    on_success: never
    on_failure: always
    on_pull_requests: never
